/* Frontend-only bridge. No shell, external navigation, network or repository effects. */
(()=>{
 const allowed=new Set(['selectTask','selectProject','addProjectForm','submitReturn','closeModal','board','byStage','create','edit','move','cancel','acceptFiles','retry','backlog','pause','resume','acceptReview','returnGate','returnMerge','settings','projectGit','stageGit','quota','mcp','identity','addProject','saveSettings','cancelSettings','clearFlag','localDiff','close','trafficClose','trafficMinimize','trafficZoom','answer','setField','setToggle']);
 const send=(action,payload={})=>{if(allowed.has(action))window.webkit?.messageHandlers?.kabanDemo?.postMessage({action,...payload});};
 const text=el=>(el?.textContent||'').trim().replace(/\s+/g,' ');
 const taskID=el=>text(el?.closest('.panel')?.querySelector('.p-id'))||text(el?.closest('.card')?.querySelector('.tid'))||'';
 const actions=[[/^Принять файлы/, 'acceptFiles'],[/^Попросить убрать/,'answer'],[/^Перезапустить|^Повторить$|^Ещё попыток/,'retry'],[/^В Backlog/,'backlog'],[/^Принять$/,'acceptReview'],[/^Вернуть/,'returnGate'],[/^Отменить задачу$|^Отменить…|^Отклонить/,'cancel'],[/^Задача$/,'create'],[/^Добавить$/,'addProject'],[/^Сохранить|^Применить$/,'saveSettings'],[/^Отменить$|^Отмена$|^Не отменять$/,'cancelSettings'],[/^Снять флаг|^Проверить снова/,'clearFlag'],[/^Открыть в Cursor|^Показать в Finder|^дифф$|^Дифф|^Восстановить в клон/,'localDiff'],[/^Указать модели|^Другая модель|^Модель$/,'settings'],[/^Настройки MCP|^MCP для запусков/,'mcp'],[/^Настройки Мака|^Настройки квоты|^Квота Cursor/,'quota'],[/^Git-политика проекта|^Права и git/,'projectGit'],[/^Ужесточить политику|^Добавить в политику/,'stageGit'],[/^Автор коммитов/,'identity'],[/^Пауза/,'pause'],[/^Возобновить|^Продолжить/,'resume']];
 document.addEventListener('contextmenu',event=>{const card=event.target.closest('.card');if(card){event.preventDefault();send('move',{taskID:taskID(card)});}});
 document.addEventListener('click',event=>{
  const el=event.target.closest('.btn,.tbtn,.sb-item,.stg,.iconbtn,.check,.switch,.preset,.lights i,.card,.lk,.lh-ic,.cbk,.cbx>span,.proj,.sb-sec,.sug,.pop.tg');if(!el)return;
  const panel=el.closest('.panel');let id=taskID(el);
  if(el.closest('.kaban-modal-host')){if(el.matches('.iconbtn')||text(el)==='Отмена'){send('closeModal');return;}if(el.matches('.sug')){send('setField',{field:'comments',value:'Убери из ветки: fixtures/orders-dump.sql, .env.local'});return;}if(el.matches('.pop.tg')){send('setField',{field:'target',value:text(el).includes('Dev')?'Test':'Dev'});return;}if(el.matches('.sh-f .primary')){send(el.closest('.apsheet')?'addProject':'submitReturn');return;}}
  if(el.matches('.proj')){send('selectProject',{project:text(el.querySelector('.pn'))});return;}
  if(el.matches('.sb-sec')&&event.target.closest('svg')){send('addProjectForm');return;}
  if(el.matches('.sb-item')&&text(el)==='Доска'){send('board');return;}
  if(el.matches('.lights i')){send(['trafficClose','trafficMinimize','trafficZoom'][[...el.parentElement.children].indexOf(el)]);return;}
  if(el.matches('.card')){send('selectTask',{taskID:id});return;}
  if(el.matches('.iconbtn')){if(el===panel?.querySelector('.iconbtn:last-child'))send('close');else send('edit',{taskID:id});return;}
  if(el.matches('.check,.switch,.cbk,.cbx>span')){el.classList.toggle('off');send('setToggle',{field:text(el.parentElement),value:!el.classList.contains('off')});return;}
  if(el.matches('.preset')){send('setField',{field:'preset',value:text(el.querySelector('b')).replace('в проекте','').trim()});return;}
  if(el.matches('.lh-ic')){send('projectGit');return;}
  const label=text(el);for(const [pattern,action]of actions){if(pattern.test(label)){send(action==='returnGate'&&/SHOP-29|Merge/.test(text(panel))?'returnMerge':action,{taskID:id,label});return;}}
  if(el.matches('.tbtn')&&/По типу стадии/.test(label)){send('byStage');return;}
  if(el.matches('.btn,.tbtn,.sb-item,.stg'))send('settings',{label});
 });
 // Original mockup span inputs become editable DOM controls without changing geometry.
 for(const input of document.querySelectorAll('.inp:not(.ro),.ap-input,.rs-input')){if(!input.matches('input,textarea')){input.contentEditable='true';input.setAttribute('role','textbox');input.addEventListener('input',()=>send('setField',{scope:input.closest('.apsheet')?'identity':'settings',field:text(input.closest('.fr,.f2,.ap-fr,.rs-fr')?.firstElementChild)||'field',value:text(input)}));}}
 for(const area of document.querySelectorAll('textarea,input'))area.addEventListener('input',()=>send('setField',{field:area.placeholder||area.name||'comments',value:area.value}));
 let originalBoard=null;
 window.kabanProject=async state=>{
  const board=document.querySelector('.board');if(board){if(originalBoard===null)originalBoard=board.innerHTML;else board.innerHTML=originalBoard;}
  document.documentElement.classList.toggle('dark',!!state.dark);document.body.classList.toggle('dark',!!state.dark);
  document.querySelector('.board')?.classList.toggle('by-stage',!!state.compact);
  for(const project of state.projects){if(![...document.querySelectorAll('.proj .pn')].some(p=>text(p)===project)){const row=document.createElement('div');row.className='proj';const mascot=document.createElement('span');mascot.className='sticker';mascot.textContent='🦊';const name=document.createElement('span');name.className='pn';name.textContent=project;row.append(mascot,name);[...document.querySelectorAll('.sidebar .proj')].at(-1)?.after(row);}if(board&&![...board.querySelectorAll('.lane .ln')].some(p=>text(p)===project)){const lane=document.createElement('div');lane.className='lane';const head=document.createElement('div');head.className='lane-h';const title=document.createElement('b');title.className='ln';title.textContent=project;head.append(title);lane.append(head);const cols=document.createElement('div');cols.className='cols';for(const stage of ['Backlog','Dev','Test','AI Review','Human Review','Merge','Done']){const col=document.createElement('div');col.className='col';const header=document.createElement('div');header.className='col-h';const b=document.createElement('b');b.textContent=stage;header.append(b);const cards=document.createElement('div');cards.className='col-cards';col.append(header,cards);cols.append(col);}lane.append(cols);board.append(lane);}}
  // Mutate actual source cards, moving them through original lane/column DOM containers.
  for(const task of state.tasks){let card=[...document.querySelectorAll('.card')].find(c=>text(c.querySelector('.tid'))===task.id);const lane=[...document.querySelectorAll('.lane')].find(l=>text(l.querySelector('.ln'))===task.project);const col=lane&&[...lane.querySelectorAll('.col')].find(c=>text(c.querySelector('.col-h b'))===task.stage);
   if(card){card.querySelector('.card-title').textContent=task.title;const foot=card.querySelector('.card-foot b');if(foot)foot.textContent=task.label;for(const cls of [...card.classList])if(cls.startsWith('st-'))card.classList.remove(cls);card.classList.add('st-'+(task.label.includes('Подмена')?'subst':task.status));const status=ST[task.status];const icon=card.querySelector('.card-foot svg');if(icon&&status)icon.outerHTML=ic(status.i,11);if(state.acceptedTaskIDs?.includes(task.id))card.querySelectorAll('.fline').forEach(e=>e.remove());if(col&&!col.contains(card)){col.querySelector('.empty')?.remove();(col.querySelector('.col-cards')||col).append(card);}}
   else if(task.id.startsWith('DEMO-')&&col){const holder=document.createElement('div');holder.innerHTML=cardTemplate(task);col.querySelector('.empty')?.remove();(col.querySelector('.col-cards')||col).append(holder.firstElementChild);}
  }
  for(const panel of document.querySelectorAll('.panel')){const id=text(panel.querySelector('.p-id'));const pending=state.pending?.includes('files:'+id);const accepted=state.acceptedTaskIDs?.includes(id);for(const button of panel.querySelectorAll('.btn')){if(/^Принять файлы|^Отправлено/.test(text(button))){button.style.pointerEvents=pending||accepted?'none':'';button.classList.toggle('pending',pending);button.textContent=pending?'Отправлено…':accepted?'Файлы приняты':'Принять файлы ('+panel.querySelectorAll('.sft .r').length+')';}}if(accepted){panel.querySelectorAll('.sft .r').forEach(row=>row.remove());const title=panel.querySelector('.susp-h b,.sf-h b');if(title)title.textContent='Файлы приняты';}}
  for(const row of document.querySelectorAll('.fr')){const name=text(row.firstElementChild);const input=row.querySelector('.inp:not(.ro)');if(input&&Object.hasOwn(state.fields||{},name)&&text(input)!==state.fields[name]&&document.activeElement!==input)input.textContent=state.fields[name];}
  for(const row of document.querySelectorAll('.sb-item')){if(text(row).startsWith('Ждут человека')){const badge=row.querySelector('.badge-n');if(badge)badge.textContent=state.waitingCount;}}
  if(state.compact&&board){const groups=new Map();for(const lane of board.querySelectorAll('.lane:not(.collapsed)')){const name=text(lane.querySelector('.ln'));for(const col of lane.querySelectorAll('.col')){const stage=text(col.querySelector('.col-h b'));if(!groups.has(stage))groups.set(stage,[]);const clone=col.cloneNode(true);clone.querySelector('.col-h b').textContent=name;clone.dataset.stage=stage;for(const card of clone.querySelectorAll('.card')){const chip=document.createElement('span');chip.className='srcchip';chip.textContent=stage;card.querySelector('.card-top')?.append(chip);}groups.get(stage).push(clone);}}const banners=board.querySelector('.banners');board.replaceChildren();if(banners)board.append(banners);for(const [stage,columns]of groups){const lane=document.createElement('div');lane.className='lane';const header=document.createElement('div');header.className='lane-h';const title=document.createElement('b');title.className='ln';title.textContent=stage;header.append(title);const cols=document.createElement('div');cols.className='cols';cols.append(...columns);lane.append(header,cols);board.append(lane);}}
  for(const preset of document.querySelectorAll('.preset'))preset.classList.toggle('on',text(preset.querySelector('b')).includes(state.preset));
  for(const toggle of document.querySelectorAll('.check,.switch,.cbk,.cbx>span')){const value=state.fields?.[text(toggle.parentElement)];if(value==='on'||value==='off')toggle.classList.toggle('off',value==='off');}
  await modal(state);
 };
 const cardTemplate=task=>{const holder=document.createElement('div');holder.innerHTML=card({p:task.project==='kaban'?'kaban':'shop',id:0,t:'',s:ST[task.status]?task.status:'queued',label:task.label});holder.querySelector('.tid').textContent=task.id;holder.querySelector('.card-title').textContent=task.title;return holder.innerHTML;};

 const escapeHTML=value=>{const e=document.createElement('div');e.textContent=value;return e.innerHTML;};
 const returnConfig=state=>{const task=state.tasks.find(t=>t.id===state.selectedTaskID);return {...(state.webModal==='return-merge'?RS_MERGE:RS_GATE),id:state.selectedTaskID||'SHOP-55',cur:task?.stage||'Checks',target:state.returnTarget,targetId:state.returnTarget.toLowerCase(),note:escapeHTML(state.returnNote)};};
 const loaded=new Map();
 const designRoot=location.href.slice(0,location.href.indexOf('/Design/')+8);
 const resource=path=>new Promise((resolve,reject)=>{if(loaded.has(path)){resolve();return;}const element=document.createElement(path.endsWith('.css')?'link':'script');if(element.tagName==='LINK'){element.rel='stylesheet';element.href=designRoot+path;}else{element.src=designRoot+path;}element.onload=()=>{loaded.set(path,true);resolve();};element.onerror=reject;document.head.append(element);});
 let modalKey='';
 const modal=async state=>{
  const key=JSON.stringify([state.webModal,state.identityMode,state.returnTarget,state.selectedTaskID]);if(key===modalKey){const note=document.querySelector('.kaban-modal-host .ta');if(note){if(document.activeElement!==note&&text(note)!==state.returnNote)note.textContent=state.returnNote;const holder=document.createElement('div');holder.innerHTML=rsPanel(returnConfig(state),!!state.returnNote.trim());for(const selector of ['.fl3','.res','.sh-f']){const current=document.querySelector('.kaban-modal-host '+selector),next=holder.querySelector(selector);if(current&&next)current.replaceWith(next);} }return;}modalKey=key;document.querySelector('.kaban-modal-host')?.remove();if(!state.webModal)return;
  await resource('v0.2.1/return-sheet.css');await resource('v0.2.1/add-project.css');await resource('v0.2.1/return-sheet.js');await resource('v0.2.1/add-project.js');
  const host=document.createElement('div');host.className='kaban-modal-host';Object.assign(host.style,{position:'fixed',inset:'0',zIndex:'80',background:'rgba(30,32,40,.11)'});
  const holder=document.createElement('div');if(state.webModal==='add')holder.innerHTML=apSheet(state.identityMode===0?'a':state.identityMode===1?'b':'c');else{const c=returnConfig(state);holder.innerHTML=rsPanel(c,!!state.returnNote.trim());}
  const sheet=holder.querySelector('.apsheet,.rsheet');Object.assign(sheet.style,{position:'absolute',width:state.webModal==='add'?'415px':'637px',left:'50%',right:'auto',top:state.webModal==='add'?'120px':'180px',transform:'translateX(-50%)'});host.append(sheet);document.body.append(host);
  for(const input of sheet.querySelectorAll('.inp')){const label=text(input.closest('.f2')?.firstElementChild);const value=/Имя/.test(label)?state.identityName:/Email|Почта/.test(label)?state.identityEmail:/Папка|Репозиторий/.test(label)?state.projectPath:'';if(value)input.textContent=value;input.contentEditable='true';input.setAttribute('role','textbox');input.addEventListener('focus',()=>input.querySelector('.ph')?.remove(),{once:true});input.addEventListener('input',()=>send('setField',{scope:'identity',field:label,value:[...input.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('')}));}
  const note=sheet.querySelector('.ta');if(note){note.contentEditable='true';note.setAttribute('role','textbox');note.addEventListener('focus',()=>note.querySelector('.ph')?.remove(),{once:true});note.addEventListener('input',()=>send('setField',{field:'comments',value:text(note)}));}
 };
})();
