import Foundation
import XCTest
import KabanProtocol
@testable import KabanKit

/// Replays the state-machine part of the Analyst's M1 scenarios (`Scenarios/M1/*.json`, read-only, generated by
/// `gen_m1.py`). The scheduler, fake driver, flags and ephemeral events belong to `KabanDaemonCore`; steps that
/// need them stop the replay (reported as "needs scheduler"). The daemon glue is mimicked minimally:
/// `completed` = complete_stage → gates → result check over `branchFiles`; a single-task `tick` = start if due.
final class ScenarioReplayTests: XCTestCase {
    /// Where the M1 scenarios come from, decided only by `KABAN_SCENARIOS` (CI: `Scenarios/M1`):
    /// - unset or empty → `.skip` (locally, and until `Scenarios/M1` lands in main);
    /// - set, and it or its `M1/` subfolder has `*.json` → `.run` (the `M1` folder itself or a `Scenarios` root);
    /// - set, but the folder is missing or neither it nor `M1/` has any `.json` → `.fail`, never a silent pass.
    enum ScenarioSource: Equatable {
        case skip(String)
        case run(URL, [String])
        case fail(String)
    }

    static func resolveScenarios(_ env: String?, fileManager fm: FileManager = .default) -> ScenarioSource {
        guard let env, !env.isEmpty else { return .skip("KABAN_SCENARIOS is not set") }
        func jsonFiles(_ url: URL) -> [String]? {
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: url.path, isDirectory: &isDir), isDir.boolValue else { return nil }
            return ((try? fm.contentsOfDirectory(atPath: url.path)) ?? []).filter { $0.hasSuffix(".json") }.sorted()
        }
        let url = URL(fileURLWithPath: env)
        guard let own = jsonFiles(url) else { return .fail("KABAN_SCENARIOS=\(env): no such directory") }
        let m1 = url.appendingPathComponent("M1")
        if let inM1 = jsonFiles(m1), !inM1.isEmpty { return .run(m1, inM1) }
        if !own.isEmpty { return .run(url, own) }
        return .fail("KABAN_SCENARIOS=\(env): no .json scenarios in it or in its M1/ subfolder")
    }

    enum Status: Equatable { case full, partial(String), skipped(String) }

    struct Report {
        var id: String
        var status: Status = .full
        var mismatches: [String] = []
        var unchecked: Set<String> = []
    }

    /// Differences between the scenarios and KabanKit that are known and listed in the report to the Architector/Analyst.
    /// M1-BOUNCE-02 used to be listed here (no total in `given`); the scenarios now carry `bounceTotal: 5` and it replays cleanly.
    static let knownMismatches: [String: Set<String>] = [:]

    /// Scenarios expected to replay completely through the state machine.
    static let expectedFull: Set<String> = [
        "M1-RETRY-01", "M1-RETRY-02", "M1-RETRY-03", "M1-RUNLIMIT-01", "M1-RUNLIMIT-02",
        "M1-NOCHARGE-daemon_restart", "M1-NOCHARGE-rate_limit", "M1-NOCHARGE-runner_auth",
        "M1-SUSP-01", "M1-SUSP-02", "M1-SUSP-03", "M1-SUSP-04", "M1-SUSP-05",
        "M1-BOUNCE-01", "M1-BOUNCE-02", "M1-CANCEL-01", "M1-FLOW-01", "M1-GIT-01", "M1-PAUSE-01", "M1-SILENT-01",
    ]

    /// The folder resolver behind `testReplayM1Scenarios`: skip / run / fail cases on temporary directories.
    func testScenarioSourceResolution() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appendingPathComponent("kaban-scenarios-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: root) }
        func mkdir(_ p: String) throws -> URL {
            let u = root.appendingPathComponent(p); try fm.createDirectory(at: u, withIntermediateDirectories: true); return u
        }
        func touch(_ p: String) throws { try Data("{}".utf8).write(to: root.appendingPathComponent(p)) }
        func isFail(_ s: ScenarioSource) -> Bool { if case .fail = s { return true }; return false }
        /// `.run` as (standardized path, files): `URL(fileURLWithPath:)` adds a trailing slash for existing directories.
        func run(_ s: ScenarioSource) -> [String]? {
            if case .run(let u, let n) = s { return [u.standardizedFileURL.path] + n }; return nil
        }
        func expect(_ u: URL, _ n: [String]) -> [String] { [u.standardizedFileURL.path] + n }

        XCTAssertEqual(Self.resolveScenarios(nil), .skip("KABAN_SCENARIOS is not set"))
        XCTAssertEqual(Self.resolveScenarios(""), .skip("KABAN_SCENARIOS is not set"))
        // Missing folder, a file instead of a folder, an empty folder, only non-JSON files, an empty M1/ → fail.
        XCTAssertTrue(isFail(Self.resolveScenarios(root.appendingPathComponent("nope").path)))
        let empty = try mkdir("empty")
        XCTAssertTrue(isFail(Self.resolveScenarios(empty.path)))
        try touch("empty/README.md")
        XCTAssertTrue(isFail(Self.resolveScenarios(empty.path)))
        _ = try mkdir("empty/M1")
        XCTAssertTrue(isFail(Self.resolveScenarios(empty.path)))
        try touch("empty/README.md.json.txt")
        XCTAssertTrue(isFail(Self.resolveScenarios(empty.path)))
        XCTAssertTrue(isFail(Self.resolveScenarios(root.appendingPathComponent("empty/README.md").path)))
        // The M1 folder itself.
        let m1 = try mkdir("Scenarios/M1")
        try touch("Scenarios/M1/b.json"); try touch("Scenarios/M1/a.json"); try touch("Scenarios/M1/notes.txt")
        XCTAssertEqual(run(Self.resolveScenarios(m1.path)), expect(m1, ["a.json", "b.json"]))
        // A Scenarios root containing M1/ (its own top-level .json, if any, are not scenarios).
        let scen = root.appendingPathComponent("Scenarios")
        XCTAssertEqual(run(Self.resolveScenarios(scen.path)), expect(m1, ["a.json", "b.json"]))
        try touch("Scenarios/index.json")
        XCTAssertEqual(run(Self.resolveScenarios(scen.path)), expect(m1, ["a.json", "b.json"]))
    }

    func testReplayM1Scenarios() throws {
        let dir: URL, names: [String]
        switch Self.resolveScenarios(ProcessInfo.processInfo.environment["KABAN_SCENARIOS"]) {
        case .skip(let why): throw XCTSkip(why)
        case .fail(let why): return XCTFail(why)
        case .run(let d, let n): dir = d; names = n
        }
        var reports: [Report] = []
        for name in names {
            let data = try Data(contentsOf: dir.appendingPathComponent(name))
            let json = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
            reports.append(try Replayer(json: json).run())
        }
        var summary: [String] = []
        for r in reports {
            let known = Self.knownMismatches[r.id] ?? []
            let unexpected = r.mismatches.filter { m in !known.contains { m.hasSuffix($0) } }
            XCTAssertTrue(unexpected.isEmpty, "\(r.id): \(unexpected.joined(separator: "; "))")
            if Self.expectedFull.contains(r.id) { XCTAssertEqual(r.status, .full, r.id) }
            let status: String
            switch r.status {
            case .full: status = "full"
            case .partial(let why): status = "partial (\(why))"
            case .skipped(let why): status = "skipped (\(why))"
            }
            let extra = r.mismatches.isEmpty ? "" : " mismatches: \(r.mismatches)"
            let un = r.unchecked.isEmpty ? "" : " unchecked: \(r.unchecked.sorted().joined(separator: ","))"
            summary.append("\(r.id): \(status)\(extra)\(un)")
        }
        print("SCENARIO REPLAY SUMMARY\n" + summary.joined(separator: "\n"))
    }
}

private final class Replayer {
    let json: [String: Any]
    var report: ScenarioReplayTests.Report
    var pipeline: PipelineConfig
    var tasks: [String: TaskMachineState] = [:]
    var order: [String] = []
    var retryAt: [String: Int] = [:]
    var accepted: [String: Set<FileBlobRef>] = [:]
    var denials: [String: Int] = [:]
    var clock = 0
    var runCounter = 100

    init(json: [String: Any]) {
        self.json = json
        report = .init(id: json["id"] as? String ?? "?")
        pipeline = TestPipelines.base
    }

    func setModel(_ stage: String, _ model: String) {
        guard let i = pipeline.stages.firstIndex(where: { $0.id.rawValue == stage }) else { return }
        pipeline.stages[i].agent?.model = ModelID(rawValue: model)
    }

    static func state(_ d: [String: Any]) -> TaskState? {
        try? KabanCoding.makeDecoder().decode(TaskState.self, from: JSONSerialization.data(withJSONObject: d))
    }

    static func seconds(_ s: String) -> Int { DurationParser.seconds(s.replacingOccurrences(of: "+", with: "")) ?? 0 }

    func run() throws -> ScenarioReplayTests.Report {
        let given = json["given"] as? [String: Any] ?? [:]
        for (stage, model) in given["stageModels"] as? [String: String] ?? [:] { setModel(stage, model) }
        for t in given["tasks"] as? [[String: Any]] ?? [] {
            let id = t["id"] as! String
            let stage = StageID(rawValue: t["stage"] as! String)
            var s = TaskMachineState(taskId: TaskID(rawValue: id), stageId: stage, state: Self.state(t["state"] as! [String: Any])!)
            if let m = t["model"] as? String { setModel(stage.rawValue, m) }
            if let run = t["runId"] as? String { s.currentRunId = RunID(rawValue: run); s.lastRunId = s.currentRunId }
            if let a = t["attempt"] as? Int { s.attemptsUsed = max(0, a - 1) }
            s.runsSinceHuman = t["autoRuns"] as? Int ?? (s.state == .running ? 1 : 0)
            // Keys are `<from>_<to>` routes; the total is not a key (README) and defaults to their sum.
            let seeded = t["bounces"] as? [String: Int] ?? [:]
            s.totalBounces = t["bounceTotal"] as? Int ?? seeded.values.reduce(0, +)
            for (k, v) in seeded {
                s.bounces[k] = v
            }
            if let files = t["suspiciousFiles"] as? [[String: Any]] {
                s.suspiciousFiles = files.map { SuspiciousFile(path: $0["path"] as! String, rule: .pattern, sizeBytes: 0, blob: $0["blob"] as! String) }
            }
            if t["retryAt"] != nil { retryAt[id] = 0 }
            tasks[id] = s
            order.append(id)
        }
        for (task, files) in given["acceptedFiles"] as? [String: [[String: String]]] ?? [:] {
            accepted[task] = Set(files.map { FileBlobRef(path: $0["path"]!, blob: $0["blob"]!) })
        }
        if given["flags"] != nil || given["modelFlags"] != nil { report.unchecked.insert("given.flags") }

        for (i, step) in (json["steps"] as? [[String: Any]] ?? []).enumerated() {
            let n = i + 1
            if step.keys.allSatisfy({ $0 == "note" }) { continue }
            if let adv = step["advance"] as? String { clock += Self.seconds(adv) }
            var effects: [TaskEffect] = []
            var commandError: String?

            if step["pipelineApplied"] != nil {
                report.status = .partial("step \(n): pipelineApplied → project flags / scheduler"); break
            }
            if let cmd = step["command"] {
                let env = try KabanCoding.makeDecoder().decode(CommandEnvelope.self, from: JSONSerialization.data(withJSONObject: cmd))
                guard let action = HumanAction(command: env.command), let taskId = Self.taskId(env.command) else {
                    report.status = .partial("step \(n): non-task command → daemon/validator"); break
                }
                let r = apply(taskId, .human(action), &effects)
                if case .rejected(let e) = r.outcome { commandError = e.code }
                daemonFollowUps(taskId, &effects)
            }
            if let drv = step["driver"] as? [String: Any] {
                guard drive(drv, &effects) else { report.status = .partial("step \(n): driver end not modelled"); break }
            }
            if step["tick"] != nil {
                let due = order.filter { id in
                    switch tasks[id]!.state { case .queued, .retryWait: return clock >= (retryAt[id] ?? 0); default: return false }
                }
                if order.count > 1 { report.status = .partial("step \(n): multi-task tick → scheduler (WIP, flags, fairness)"); break }
                for id in due {
                    runCounter += 1
                    _ = apply(id, .start(runId: RunID(rawValue: "r-\(runCounter)")), &effects)
                }
            }
            if let then = step["then"] as? [String: Any] { verify(n, then, effects, commandError) }
        }
        return report
    }

    static func taskId(_ c: Command) -> String? {
        switch c {
        case .answerHuman(let t, _, _), .approve(let t), .requestChanges(let t, _, _), .reject(let t, _, _), .pauseTask(let t),
             .resumeTask(let t), .moveTask(let t, _), .retryStage(let t, _), .cancelTask(let t, _), .acceptSuspiciousFiles(let t, _):
            return t.rawValue
        default: return nil
        }
    }

    @discardableResult
    func apply(_ id: String, _ e: TaskEvent, _ effects: inout [TaskEffect]) -> TransitionResult {
        let r = TaskMachine.transition(tasks[id]!, e, pipeline: pipeline)
        tasks[id] = r.state
        effects += r.effects
        for case .scheduleRetry(let after, _) in r.effects { retryAt[id] = clock + after }
        for case .acceptSuspiciousFiles(let files) in r.effects {
            accepted[id, default: []].formUnion(files.map { FileBlobRef(path: $0.path, blob: $0.blob) })
        }
        return r
    }

    var lastBranchFiles: [String: [ChangedFile]] = [:]

    /// The daemon's own reaction to effects: result check over the current branch diff.
    func daemonFollowUps(_ id: String, _ effects: inout [TaskEffect]) {
        var guardCount = 0
        while guardCount < 5, case .runResultCheck? = effects.last {
            guardCount += 1
            let found = SuspiciousFilesScanner.scan(lastBranchFiles[id] ?? [], policy: pipeline.suspiciousFiles, accepted: accepted[id] ?? [])
            apply(id, .resultChecked(found.isEmpty ? .clean : .suspiciousFiles(found)), &effects)
        }
    }

    func drive(_ d: [String: Any], _ effects: inout [TaskEffect]) -> Bool {
        let id = d["task"] as! String
        guard let run = tasks[id]?.currentRunId else { return false }
        if let n = d["gitDenied"] as? Int {
            denials[id, default: 0] += n
            if denials[id]! >= 5 { apply(id, .gitDenialLimit(runId: run), &effects) }
            return true
        }
        if let files = d["branchFiles"] as? [[String: Any]] {
            lastBranchFiles[id] = files.map { ChangedFile(path: $0["path"] as! String, sizeBytes: Int64($0["sizeBytes"] as! Int), blob: $0["blob"] as! String) }
        }
        switch d["end"] as? String {
        case "completed":
            apply(id, .completeStage(runId: run, summary: "done"), &effects)
            if d["gates"] as? String == "red" { apply(id, .gatesFailed(output: "red"), &effects); return true }
            apply(id, .gatesPassed, &effects)
            daemonFollowUps(id, &effects)
        case "gate_failed":
            apply(id, .completeStage(runId: run, summary: "done"), &effects)
            apply(id, .gatesFailed(output: "red"), &effects)
        case "crash": apply(id, .runEnded(runId: run, .crash), &effects)
        case "stall_timeout": apply(id, .runEnded(runId: run, .stallTimeout), &effects)
        case "wall_timeout": apply(id, .runEnded(runId: run, .wallTimeout), &effects)
        case "no_final_call": apply(id, .runEnded(runId: run, .noFinalCall), &effects)
        case "rate_limit": apply(id, .runEnded(runId: run, .rateLimit), &effects)
        case "runner_auth": apply(id, .runEnded(runId: run, .runnerAuth), &effects)
        case "silent_exit": apply(id, .runEnded(runId: run, .silentExit), &effects)
        case "daemon_restart": apply(id, .daemonRestarted, &effects)
        case "model_substituted":
            let stage = tasks[id]!.stageId
            apply(id, .modelMismatch(runId: run, requested: pipeline.stage(stage)?.agent?.model?.rawValue ?? "?",
                                     actual: d["actual"] as? String ?? "?", fallback: nil), &effects)
        case "returned": apply(id, .returnToStage(runId: run, target: StageID(rawValue: d["to"] as! String), issues: ["issue"]), &effects)
        case "asked_human": apply(id, .requestHuman(runId: run, question: d["question"] as? String ?? "?"), &effects)
        default: return false
        }
        return true
    }

    func verify(_ n: Int, _ then: [String: Any], _ effects: [TaskEffect], _ commandError: String?) {
        func miss(_ s: String) { report.mismatches.append("step \(n) \(s)") }
        for (id, exp) in then["tasks"] as? [String: [String: Any]] ?? [:] {
            guard let s = tasks[id] else { miss("unknown task \(id)"); continue }
            if let st = exp["stage"] as? String, st != s.stageId.rawValue { miss("\(id).stage: expected \(st), got \(s.stageId)") }
            if let st = exp["state"] as? [String: Any], let want = Self.state(st), want != s.state {
                // `queued(wip_full)` is a scheduler label; the machine yields plain `queued`.
                if !(want.status == .queued && s.state == .queued(nil)) { miss("\(id).state: expected \(want), got \(s.state)") }
                else { report.unchecked.insert("queued label") }
            }
            if let a = exp["attempt"] as? Int, let stage = pipeline.stage(s.stageId), a != s.displayAttempt(stage) {
                miss("\(id).attempt: expected \(a), got \(s.displayAttempt(stage))")
            }
            if let r = exp["autoRuns"] as? Int, r != s.runsSinceHuman { miss("\(id).autoRuns: expected \(r), got \(s.runsSinceHuman)") }
            if let b = exp["bounces"] as? [String: Int] {
                for (k, v) in b where (k == "total" ? s.totalBounces : s.bounces[k] ?? 0) != v { miss("\(id).bounces[\(k)]: expected \(v)") }
            }
            if let ra = exp["retryAt"] as? String, retryAt[id] != clock + Self.seconds(ra) {
                miss("\(id).retryAt: expected \(ra), got +\((retryAt[id] ?? 0) - clock)s")
            }
        }
        if let code = then["commandError"] as? String, code != commandError { miss("commandError: expected \(code), got \(commandError ?? "none")") }
        if let started = then["runsStarted"] as? Int, started != effects.startedRuns.count { miss("runsStarted: expected \(started), got \(effects.startedRuns.count)") }
        if let killed = then["runsKilled"] as? Int {
            let k = effects.filter { if case .killRun = $0 { return true }; return false }.count
            if killed != k { miss("runsKilled: expected \(killed), got \(k)") }
        }
        for (id, how) in then["clone"] as? [String: String] ?? [:] {
            _ = id
            let reset = effects.contains { if case .saveWipAndRollback = $0 { return true }; return false }
            if (how == "reset") != reset { miss("clone: expected \(how)") }
        }
        for ref in then["refs"] as? [String] ?? [] {
            let ok = ref.hasPrefix("refs/kaban/wip/") ? effects.contains { if case .saveWipAndRollback = $0 { return true }; return false }
                : ref.hasPrefix("kaban/archive/") ? effects.contains(.cleanupClone(keepBranch: true)) : false
            if !ok { miss("refs: expected \(ref)") }
        }
        if let files = then["acceptedFiles"] as? [String: [[String: String]]] {
            for (id, list) in files where Set(list.map { FileBlobRef(path: $0["path"]!, blob: $0["blob"]!) }) != accepted[id] ?? [] {
                miss("acceptedFiles[\(id)] differ")
            }
        }
        if let events = then["events"] as? [[String: Any]] { verifyEvents(n, events, effects) }
        for key in ["flags", "ephemeral", "probes", "runningByProject", "runEnd"] where then[key] != nil { report.unchecked.insert(key) }
    }

    func verifyEvents(_ n: Int, _ events: [[String: Any]], _ effects: [TaskEffect]) {
        var transitions = effects.transitions
        let encoder = KabanCoding.makeEncoder()
        if events.isEmpty, effects.contains(where: { if case .recordTransition = $0 { return true }; return false }) {
            report.mismatches.append("step \(n) events: expected none")
        }
        var idx = 0
        for e in events {
            let type = e["type"] as! String
            let data = e["data"] as? [String: Any] ?? [:]
            switch type {
            case "taskTransitioned":
                guard !transitions.isEmpty else { report.mismatches.append("step \(n) event taskTransitioned missing"); continue }
                let t = transitions.removeFirst()
                let actual = (try? JSONSerialization.jsonObject(with: encoder.encode(t))) as? [String: Any] ?? [:]
                for (k, v) in data where !Self.equal(actual[k], v) {
                    report.mismatches.append("step \(n) event taskTransitioned[\(idx)].\(k): expected \(Self.text(v)), got \(Self.text(actual[k]))")
                }
                idx += 1
            case "suspiciousFilesFound":
                guard let files = effects.compactMap({ if case .reportSuspiciousFiles(let f, _) = $0 { return f }; return nil }).last else {
                    report.mismatches.append("step \(n) event suspiciousFilesFound missing"); continue
                }
                let want = (data["files"] as? [[String: Any]] ?? []).map { "\($0["path"]!)|\($0["rule"]!)" }
                let got = files.map { "\($0.path)|\($0.rule.rawValue)" }
                if want != got { report.mismatches.append("step \(n) suspiciousFilesFound files: expected \(want), got \(got)") }
            case "suspiciousFilesAccepted":
                if effects.accepted == nil { report.mismatches.append("step \(n) event suspiciousFilesAccepted missing") }
            case "humanRequested":
                if !effects.contains(where: { if case .recordHumanRequest = $0 { return true }; return false }) {
                    report.mismatches.append("step \(n) event humanRequested missing")
                }
            default:
                report.unchecked.insert("event \(type)")
            }
        }
    }

    static func text(_ v: Any?) -> String {
        guard let v else { return "nil" }
        if let d = v as? [String: Any] { return (d["status"] as? String ?? "") + ((d["reason"] as? String).map { ":" + $0 } ?? "") }
        return "\(v)"
    }

    static func equal(_ a: Any?, _ b: Any) -> Bool {
        guard let a else { return false }
        if let x = a as? [String: Any], let y = b as? [String: Any] {
            return x.count == y.count && y.allSatisfy { k, v in equal(x[k], v) }
        }
        return "\(a)" == "\(b)"
    }
}
